{
    "location": {
        "name": "Galway",
        "region": "Galway",
        "country": "Ireland",
        "lat": 53.27,
        "lon": -9.05,
        "tz_id": "Europe/Dublin",
        "localtime_epoch": 1723912206,
        "localtime": "2024-08-17 17:30"
    },
    "current": {
        "last_updated_epoch": 1723912200,
        "last_updated": "2024-08-17 17:30",
        "temp_c": 15.9,
        "temp_f": 60.6,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 16.6,
        "wind_kph": 26.6,
        "wind_degree": 243,
        "wind_dir": "WSW",
        "pressure_mb": 1011,
        "pressure_in": 29.85,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 73,
        "cloud": 8,
        "feelslike_c": 15.9,
        "feelslike_f": 60.6,
        "windchill_c": 15.9,
        "windchill_f": 60.6,
        "heatindex_c": 15.9,
        "heatindex_f": 60.6,
        "dewpoint_c": 11.1,
        "dewpoint_f": 52,
        "vis_km": 10,
        "vis_miles": 6,
        "uv": 5,
        "gust_mph": 21.7,
        "gust_kph": 35
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2024-08-17",
                "date_epoch": 1723852800,
                "day": {
                    "maxtemp_c": 16.3,
                    "maxtemp_f": 61.3,
                    "mintemp_c": 13.3,
                    "mintemp_f": 55.9,
                    "avgtemp_c": 14.9,
                    "avgtemp_f": 58.7,
                    "maxwind_mph": 17.9,
                    "maxwind_kph": 28.8,
                    "totalprecip_mm": 0.72,
                    "totalprecip_in": 0.03,
                    "totalsnow_cm": 0,
                    "avgvis_km": 10,
                    "avgvis_miles": 6,
                    "avghumidity": 76,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 89,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "uv": 4
                },
                "astro": {
                    "sunrise": "06:20 AM",
                    "sunset": "08:59 PM",
                    "moonrise": "08:34 PM",
                    "moonset": "02:17 AM",
                    "moon_phase": "Waxing Gibbous",
                    "moon_illumination": 90,
                    "is_moon_up": 1,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1723849200,
                        "time": "2024-08-17 00:00",
                        "temp_c": 14.6,
                        "temp_f": 58.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 15.2,
                        "wind_kph": 24.5,
                        "wind_degree": 243,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013,
                        "pressure_in": 29.92,
                        "precip_mm": 0.02,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 73,
                        "cloud": 88,
                        "feelslike_c": 12.9,
                        "feelslike_f": 55.2,
                        "windchill_c": 12.9,
                        "windchill_f": 55.2,
                        "heatindex_c": 14.6,
                        "heatindex_f": 58.3,
                        "dewpoint_c": 9.9,
                        "dewpoint_f": 49.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 81,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 23.2,
                        "gust_kph": 37.3,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723852800,
                        "time": "2024-08-17 01:00",
                        "temp_c": 14.6,
                        "temp_f": 58.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 15.4,
                        "wind_kph": 24.8,
                        "wind_degree": 244,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013,
                        "pressure_in": 29.92,
                        "precip_mm": 0.03,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 74,
                        "cloud": 89,
                        "feelslike_c": 12.8,
                        "feelslike_f": 55.1,
                        "windchill_c": 12.8,
                        "windchill_f": 55.1,
                        "heatindex_c": 14.6,
                        "heatindex_f": 58.2,
                        "dewpoint_c": 10,
                        "dewpoint_f": 50.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 80,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 23.2,
                        "gust_kph": 37.4,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723856400,
                        "time": "2024-08-17 02:00",
                        "temp_c": 14.4,
                        "temp_f": 57.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 15,
                        "wind_kph": 24.1,
                        "wind_degree": 247,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013,
                        "pressure_in": 29.91,
                        "precip_mm": 0.03,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 76,
                        "cloud": 86,
                        "feelslike_c": 12.6,
                        "feelslike_f": 54.7,
                        "windchill_c": 12.6,
                        "windchill_f": 54.7,
                        "heatindex_c": 14.4,
                        "heatindex_f": 57.8,
                        "dewpoint_c": 10.3,
                        "dewpoint_f": 50.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 62,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 22.7,
                        "gust_kph": 36.5,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723860000,
                        "time": "2024-08-17 03:00",
                        "temp_c": 14.2,
                        "temp_f": 57.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 13.9,
                        "wind_kph": 22.3,
                        "wind_degree": 244,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.9,
                        "precip_mm": 0.06,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 78,
                        "cloud": 84,
                        "feelslike_c": 12.5,
                        "feelslike_f": 54.5,
                        "windchill_c": 12.5,
                        "windchill_f": 54.5,
                        "heatindex_c": 14.2,
                        "heatindex_f": 57.5,
                        "dewpoint_c": 10.5,
                        "dewpoint_f": 50.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21,
                        "gust_kph": 33.8,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723863600,
                        "time": "2024-08-17 04:00",
                        "temp_c": 14.2,
                        "temp_f": 57.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 14.1,
                        "wind_kph": 22.7,
                        "wind_degree": 244,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.89,
                        "precip_mm": 0.05,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 79,
                        "cloud": 90,
                        "feelslike_c": 12.5,
                        "feelslike_f": 54.4,
                        "windchill_c": 12.5,
                        "windchill_f": 54.4,
                        "heatindex_c": 14.2,
                        "heatindex_f": 57.5,
                        "dewpoint_c": 10.5,
                        "dewpoint_f": 51,
                        "will_it_rain": 1,
                        "chance_of_rain": 78,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21.1,
                        "gust_kph": 34,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723867200,
                        "time": "2024-08-17 05:00",
                        "temp_c": 14.1,
                        "temp_f": 57.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 14.1,
                        "wind_kph": 22.7,
                        "wind_degree": 245,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.89,
                        "precip_mm": 0.04,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 79,
                        "cloud": 93,
                        "feelslike_c": 12.4,
                        "feelslike_f": 54.2,
                        "windchill_c": 12.4,
                        "windchill_f": 54.2,
                        "heatindex_c": 14.1,
                        "heatindex_f": 57.4,
                        "dewpoint_c": 10.6,
                        "dewpoint_f": 51.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 72,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21,
                        "gust_kph": 33.8,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723870800,
                        "time": "2024-08-17 06:00",
                        "temp_c": 14.1,
                        "temp_f": 57.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 13.6,
                        "wind_kph": 22,
                        "wind_degree": 242,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.9,
                        "precip_mm": 0.04,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 80,
                        "cloud": 92,
                        "feelslike_c": 12.4,
                        "feelslike_f": 54.2,
                        "windchill_c": 12.4,
                        "windchill_f": 54.2,
                        "heatindex_c": 14.1,
                        "heatindex_f": 57.3,
                        "dewpoint_c": 10.7,
                        "dewpoint_f": 51.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 75,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 20.4,
                        "gust_kph": 32.8,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723874400,
                        "time": "2024-08-17 07:00",
                        "temp_c": 14.4,
                        "temp_f": 57.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 14.1,
                        "wind_kph": 22.7,
                        "wind_degree": 239,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013,
                        "pressure_in": 29.9,
                        "precip_mm": 0.07,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 81,
                        "cloud": 93,
                        "feelslike_c": 12.7,
                        "feelslike_f": 54.9,
                        "windchill_c": 12.7,
                        "windchill_f": 54.9,
                        "heatindex_c": 14.4,
                        "heatindex_f": 57.8,
                        "dewpoint_c": 11.1,
                        "dewpoint_f": 52,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 20.3,
                        "gust_kph": 32.7,
                        "uv": 3
                    },
                    {
                        "time_epoch": 1723878000,
                        "time": "2024-08-17 08:00",
                        "temp_c": 14.7,
                        "temp_f": 58.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 14.8,
                        "wind_kph": 23.8,
                        "wind_degree": 239,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013,
                        "pressure_in": 29.91,
                        "precip_mm": 0.05,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 79,
                        "cloud": 85,
                        "feelslike_c": 13.1,
                        "feelslike_f": 55.5,
                        "windchill_c": 13.1,
                        "windchill_f": 55.5,
                        "heatindex_c": 14.7,
                        "heatindex_f": 58.5,
                        "dewpoint_c": 11.2,
                        "dewpoint_f": 52.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 20.8,
                        "gust_kph": 33.5,
                        "uv": 3
                    },
                    {
                        "time_epoch": 1723881600,
                        "time": "2024-08-17 09:00",
                        "temp_c": 15,
                        "temp_f": 59,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 15,
                        "wind_kph": 24.1,
                        "wind_degree": 236,
                        "wind_dir": "WSW",
                        "pressure_mb": 1013,
                        "pressure_in": 29.9,
                        "precip_mm": 0.05,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 78,
                        "cloud": 80,
                        "feelslike_c": 15,
                        "feelslike_f": 59.1,
                        "windchill_c": 15,
                        "windchill_f": 59.1,
                        "heatindex_c": 15,
                        "heatindex_f": 59.1,
                        "dewpoint_c": 11.2,
                        "dewpoint_f": 52.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 70,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 20.4,
                        "gust_kph": 32.8,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723885200,
                        "time": "2024-08-17 10:00",
                        "temp_c": 15.6,
                        "temp_f": 60.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 16.8,
                        "wind_kph": 27,
                        "wind_degree": 235,
                        "wind_dir": "SW",
                        "pressure_mb": 1013,
                        "pressure_in": 29.91,
                        "precip_mm": 0.05,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 75,
                        "cloud": 90,
                        "feelslike_c": 15.6,
                        "feelslike_f": 60.2,
                        "windchill_c": 15.6,
                        "windchill_f": 60.2,
                        "heatindex_c": 15.6,
                        "heatindex_f": 60.2,
                        "dewpoint_c": 11.2,
                        "dewpoint_f": 52.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 71,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21.4,
                        "gust_kph": 34.5,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723888800,
                        "time": "2024-08-17 11:00",
                        "temp_c": 15.9,
                        "temp_f": 60.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 16.8,
                        "wind_kph": 27,
                        "wind_degree": 236,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.9,
                        "precip_mm": 0.03,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 72,
                        "cloud": 76,
                        "feelslike_c": 15.9,
                        "feelslike_f": 60.5,
                        "windchill_c": 15.9,
                        "windchill_f": 60.5,
                        "heatindex_c": 15.9,
                        "heatindex_f": 60.5,
                        "dewpoint_c": 10.9,
                        "dewpoint_f": 51.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 66,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21.5,
                        "gust_kph": 34.7,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723892400,
                        "time": "2024-08-17 12:00",
                        "temp_c": 16.2,
                        "temp_f": 61.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 17.7,
                        "wind_kph": 28.4,
                        "wind_degree": 237,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.89,
                        "precip_mm": 0.04,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 70,
                        "cloud": 82,
                        "feelslike_c": 16.2,
                        "feelslike_f": 61.2,
                        "windchill_c": 16.2,
                        "windchill_f": 61.2,
                        "heatindex_c": 16.2,
                        "heatindex_f": 61.2,
                        "dewpoint_c": 10.7,
                        "dewpoint_f": 51.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 71,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 22.3,
                        "gust_kph": 35.9,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723896000,
                        "time": "2024-08-17 13:00",
                        "temp_c": 16.2,
                        "temp_f": 61.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 17.4,
                        "wind_kph": 28.1,
                        "wind_degree": 236,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.89,
                        "precip_mm": 0.02,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 70,
                        "cloud": 77,
                        "feelslike_c": 16.2,
                        "feelslike_f": 61.2,
                        "windchill_c": 16.2,
                        "windchill_f": 61.2,
                        "heatindex_c": 16.2,
                        "heatindex_f": 61.2,
                        "dewpoint_c": 10.7,
                        "dewpoint_f": 51.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 62,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 22,
                        "gust_kph": 35.4,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723899600,
                        "time": "2024-08-17 14:00",
                        "temp_c": 16.2,
                        "temp_f": 61.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 17.9,
                        "wind_kph": 28.8,
                        "wind_degree": 236,
                        "wind_dir": "WSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.88,
                        "precip_mm": 0.02,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 71,
                        "cloud": 84,
                        "feelslike_c": 16.2,
                        "feelslike_f": 61.1,
                        "windchill_c": 16.2,
                        "windchill_f": 61.1,
                        "heatindex_c": 16.2,
                        "heatindex_f": 61.1,
                        "dewpoint_c": 11,
                        "dewpoint_f": 51.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 66,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 22.7,
                        "gust_kph": 36.5,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723903200,
                        "time": "2024-08-17 15:00",
                        "temp_c": 16.2,
                        "temp_f": 61.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 17.2,
                        "wind_kph": 27.7,
                        "wind_degree": 238,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.86,
                        "precip_mm": 0.02,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 70,
                        "cloud": 79,
                        "feelslike_c": 16.2,
                        "feelslike_f": 61.1,
                        "windchill_c": 16.2,
                        "windchill_f": 61.1,
                        "heatindex_c": 16.2,
                        "heatindex_f": 61.1,
                        "dewpoint_c": 10.7,
                        "dewpoint_f": 51.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 76,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 22.4,
                        "gust_kph": 36.1,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723906800,
                        "time": "2024-08-17 16:00",
                        "temp_c": 16.3,
                        "temp_f": 61.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 17.9,
                        "wind_kph": 28.8,
                        "wind_degree": 239,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.86,
                        "precip_mm": 0.03,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 70,
                        "cloud": 92,
                        "feelslike_c": 16.3,
                        "feelslike_f": 61.3,
                        "windchill_c": 16.3,
                        "windchill_f": 61.3,
                        "heatindex_c": 16.3,
                        "heatindex_f": 61.3,
                        "dewpoint_c": 10.8,
                        "dewpoint_f": 51.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 73,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 23.2,
                        "gust_kph": 37.4,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723910400,
                        "time": "2024-08-17 17:00",
                        "temp_c": 15.9,
                        "temp_f": 60.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 16.6,
                        "wind_kph": 26.6,
                        "wind_degree": 243,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.85,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 73,
                        "cloud": 8,
                        "feelslike_c": 15.9,
                        "feelslike_f": 60.6,
                        "windchill_c": 15.9,
                        "windchill_f": 60.6,
                        "heatindex_c": 15.9,
                        "heatindex_f": 60.6,
                        "dewpoint_c": 11.1,
                        "dewpoint_f": 52,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21.7,
                        "gust_kph": 35,
                        "uv": 5
                    },
                    {
                        "time_epoch": 1723914000,
                        "time": "2024-08-17 18:00",
                        "temp_c": 15.2,
                        "temp_f": 59.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 15.9,
                        "wind_kph": 25.6,
                        "wind_degree": 252,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.84,
                        "precip_mm": 0.01,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 77,
                        "cloud": 73,
                        "feelslike_c": 15.2,
                        "feelslike_f": 59.4,
                        "windchill_c": 15.2,
                        "windchill_f": 59.4,
                        "heatindex_c": 15.2,
                        "heatindex_f": 59.4,
                        "dewpoint_c": 11.2,
                        "dewpoint_f": 52.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 82,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21.4,
                        "gust_kph": 34.4,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1723917600,
                        "time": "2024-08-17 19:00",
                        "temp_c": 14.5,
                        "temp_f": 58.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 14.8,
                        "wind_kph": 23.8,
                        "wind_degree": 251,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.84,
                        "precip_mm": 0.03,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 80,
                        "cloud": 76,
                        "feelslike_c": 12.8,
                        "feelslike_f": 55,
                        "windchill_c": 12.8,
                        "windchill_f": 55,
                        "heatindex_c": 14.5,
                        "heatindex_f": 58,
                        "dewpoint_c": 11.1,
                        "dewpoint_f": 51.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21.6,
                        "gust_kph": 34.8,
                        "uv": 3
                    },
                    {
                        "time_epoch": 1723921200,
                        "time": "2024-08-17 20:00",
                        "temp_c": 13.7,
                        "temp_f": 56.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 13.4,
                        "wind_kph": 21.6,
                        "wind_degree": 252,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.84,
                        "precip_mm": 0.02,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 81,
                        "cloud": 80,
                        "feelslike_c": 11.9,
                        "feelslike_f": 53.5,
                        "windchill_c": 11.9,
                        "windchill_f": 53.5,
                        "heatindex_c": 13.7,
                        "heatindex_f": 56.7,
                        "dewpoint_c": 10.5,
                        "dewpoint_f": 50.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 85,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 21.6,
                        "gust_kph": 34.7,
                        "uv": 3
                    },
                    {
                        "time_epoch": 1723924800,
                        "time": "2024-08-17 21:00",
                        "temp_c": 13.5,
                        "temp_f": 56.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 14.5,
                        "wind_kph": 23.4,
                        "wind_degree": 255,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.86,
                        "precip_mm": 0.01,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 79,
                        "cloud": 75,
                        "feelslike_c": 11.5,
                        "feelslike_f": 52.7,
                        "windchill_c": 11.5,
                        "windchill_f": 52.7,
                        "heatindex_c": 13.5,
                        "heatindex_f": 56.2,
                        "dewpoint_c": 10,
                        "dewpoint_f": 50,
                        "will_it_rain": 0,
                        "chance_of_rain": 65,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 23.8,
                        "gust_kph": 38.3,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723928400,
                        "time": "2024-08-17 22:00",
                        "temp_c": 13.3,
                        "temp_f": 55.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 14.3,
                        "wind_kph": 23,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.86,
                        "precip_mm": 0.01,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 79,
                        "cloud": 63,
                        "feelslike_c": 11.3,
                        "feelslike_f": 52.3,
                        "windchill_c": 11.3,
                        "windchill_f": 52.3,
                        "heatindex_c": 13.3,
                        "heatindex_f": 55.9,
                        "dewpoint_c": 9.7,
                        "dewpoint_f": 49.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 62,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 23.3,
                        "gust_kph": 37.4,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1723932000,
                        "time": "2024-08-17 23:00",
                        "temp_c": 13.6,
                        "temp_f": 56.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 15,
                        "wind_kph": 24.1,
                        "wind_degree": 254,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.86,
                        "precip_mm": 0.01,
                        "precip_in": 0,
                        "snow_cm": 0,
                        "humidity": 78,
                        "cloud": 75,
                        "feelslike_c": 11.6,
                        "feelslike_f": 52.9,
                        "windchill_c": 11.6,
                        "windchill_f": 52.9,
                        "heatindex_c": 13.6,
                        "heatindex_f": 56.4,
                        "dewpoint_c": 9.8,
                        "dewpoint_f": 49.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 82,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 24.3,
                        "gust_kph": 39.2,
                        "uv": 0
                    }
                ]
            }
        ]
    }
}