const conditions = {
    'sunny': '☀️',
    'partly cloudy': '🌤️',
    'cloudy': '☁️',
    'overcast': '🌥️',
    'mist': '🌫️',
    'patchy rain possible': '🌦️',
    'patchy rain nearby': '🌦️',
    'patchy snow possible': '🌨️',
    'patchy sleet possible': '🌨️',
    'patchy freezing drizzle possible': '❄️',
    'thundery outbreaks possible': '⛈️',
    'blowing snow': '🌬️',
    'blizzard': '🌨️',
    'fog': '🌫️',
    'freezing fog': '❄️',
    'patchy light drizzle': '🌧️',
    'light drizzle': '🌦️',
    'moderate rain at times': '🌧️',
    'moderate rain': '🌧️',
    'heavy freezing drizzle': '❄️',
    'heavy rain at times': '🌧️',
    'heavy rain': '🌧️',
    'light freezing rain': '🌨️',
    'moderate or heavy freezing rain': '🌨️',
    'light sleet': '🌨️',
    'moderate or heavy sleet': '🌨️',
    'patchy light snow': '🌨️',
    'light snow': '🌨️',
    'patchy moderate snow': '🌨️',
    'moderate snow': '🌨️',
    'patchy heavy snow': '🌨️',
    'heavy snow': '❄️',
    'ice pellets': '🧊',
    'light rain shower': '🌦️',
    'moderate or heavy rain shower': '🌧️',
    'torrential rain shower': '🌧️',
    'light sleet showers': '🌨️',
    'moderate or heavy sleet showers': '🌨️',
    'light snow showers': '🌨️',
    'moderate or heavy snow showers': '❄️',
    'light showers of ice pellets': '🧊',
    'moderate or heavy showers of ice pellets': '🧊',
    'patchy light rain with thunder': '🌩️',
    'moderate or heavy rain with thunder': '🌩️',
    'patchy light snow with thunder': '⛈️',
    'moderate or heavy snow with thunder': '⛈️',
}

export default conditions;
